ci: replace get-latest-release with github cli (#27)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,6 +26,7 @@ jobs:
       FGA_VERSION_CODE: 0
       FGA_VERSION_NAME: ''
       COMMIT_LOGS: ''
+      TAG_NAME: ''
     permissions:
       contents: write
       discussions: write
@@ -36,13 +37,25 @@ jobs:
           fetch-depth: 0
           repository: 'ArthurKun21/FGA-Preview'
           token: ${{ secrets.PAT }}
-      - name: Get previous release
-        id: last_release
-        uses: InsonusK/get-latest-release@7a9ff16c8c6b7ead5d71c0f1cc61f2703170eade # v1.1.0
+      
+      - name: Checkout code
+        uses: actions/checkout@v4
         with:
-          myToken: ${{ github.token }}
-          exclude_types: "draft|prerelease"
-          view_top: 1
+          fetch-depth: 0
+          path: 'preview'
+      - name: Get previous release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          cd preview
+          OUTPUT=$(gh release list --exclude-drafts --exclude-pre-releases --json tagName --limit 1 --jq 'select(length > 0) | .[0].tagName')
+          if [ -n "$OUTPUT" ]; then
+            echo "TAG_NAME=$OUTPUT" >> $GITHUB_ENV
+            echo "Latest Tag: $OUTPUT"
+          else
+            echo "Failed to get repository information"
+            exit 1
+          fi
       - name: Prepare build
         id: prepare_build
         run: |
@@ -54,7 +67,7 @@ jobs:
           echo "FGA_VERSION_CODE=$commit_count" >>${GITHUB_ENV}
           echo "FGA_VERSION_NAME=$current_sha" >>${GITHUB_ENV}
 
-          prev_commit_count=$(echo "${{ steps.last_release.outputs.tag_name }}" | sed -e "s/^pre-//")
+          prev_commit_count=$(echo "${{ env.TAG_NAME }}" | sed -e "s/^pre-//")
 
           commit_count_diff=$(($commit_count - $prev_commit_count))
           echo "commit_count_diff=$commit_count_diff" >> $GITHUB_ENV
